### ISSUE TITLE
Możliwość dodania dowolnej liczby osiągnięć

### ISSUE THREAD

**Issue by Gumkle** [akai-org/AKAI-generator-wnioskow#1]
Nie zafixowane trzy a elastycznie

**Comment by madragonse** [comment]
Przydała by się też opcja usunięcia okienka na osiągnięcie, w przypadku kiedy ktoś sobie ich za dużo doda

**Comment by Gumkle** [comment]
Mysle ze masz rację, ale to case na osobny issue ze wzgledu na to ze teraz jezeli jedno z osiągnięć bedzie puste to backend je po prostu pomija, co czyni z tego nie tyle błąd co mala niedogodność ui/ux.
