### ISSUE TITLE
Logo polibudy w tle

### ISSUE THREAD

**Issue by Gumkle** [akai-org/AKAI-generator-wnioskow#13]
Fajny akcent z tym logiem polibudy w tle, ale moim zdaniem za bardzo pcha się na pierwszy plan i warto tu pokombinować z opacity, przestawić na 1/4 albo coś koło tej wartości. Co o tym myślicie @marcinlawnik @kalkson @madragonse?

![Screenshot_20201001_204346](https://user-images.githubusercontent.com/24682682/94850170-d09ab400-0426-11eb-9694-9ba252d0360c.png)

**Comment by madragonse** [comment]
Trochę powiększyłem logo i zamgliłem je. Zastanawiam się też czy gdyby je jeszcze bardziej powiększyć i wyśrodkować czy nie było by lepiej.

**Comment by kalkson** [comment]
Poprawka w #16 
Tak się złożyło że requestujemy akurat w tym samym czasie co @madragonse :/

**Comment by Gumkle** [comment]
Resolved #15
