### ISSUE TITLE
Nieprawidłowe priorytety w autouzupełnianiu pól

### ISSUE THREAD

**Issue by Gumkle** [akai-org/AKAI-generator-wnioskow#33]
W aplikacji pola można uzupełniać automatycznie na dwa sposoby: podając wartości pól w argumentach GET w linku i przez ciasteczka. Zostało mi trochę tych ciasteczek po ostatnim wypełnianiu w ramach debugu więc jak wszedłem na stronę to od razu mi się uzupełniły pola na ich podstawie. Problem w tym, że wszedłem przez link z danymi podanymi w GET, z linku przesłanego przez przewo innego koła. Czy nie powinno być tak, że dane w GET powinny mieć priorytet ponad tym, co znajduje się w cookies? Wydaje się to rozsądniejsze.

**Comment by roertbb** [comment]
@Gumkle możesz rzucić okiem dla sanity czy działa zgodnie z założeniami? 🙏

**Comment by Gumkle** [comment]
Sory za dwa tygodnie bez odzewu, miałem powiadomienie ale odczytałem, zamknąłem i zapomniałem xD

Ogólnie wygląda spoko poza tym, że teraz w ogóle nie ładuje mi danych ze storage, nawet przy braku argumentów GET. Z tego co widzę to już pomergowane, closowane i deployowane więc zakładam osobnego issue do buga #35
