### ISSUE TITLE
Pola formularza nie uzupełniają się z localStorage

### ISSUE THREAD

**Issue by Gumkle** [akai-org/AKAI-generator-wnioskow#35]
Po zmergowaniu #34 w ramach #33 pola formularza nie uzupełniają się danymi z localStorage. Problem występuje na prodzie i na localu pod dockerem. Nie debugowałem tego dalej, sprawdziłem tylko, że przy f6017bf161dd84e9bfdcd96e0f6258d81ba8372c działa ok.

**Comment by roertbb** [comment]
fixed in https://github.com/akai-org/AKAI-generator-wnioskow/pull/37
