### ISSUE TITLE
Umieszczenie stópki

### ISSUE THREAD

**Issue by Gumkle** [akai-org/AKAI-generator-wnioskow#6]
Stópka strony z linkiem do repozytorium i informacją o stworzeniu jej przez AKAI

**Comment by marcinlawnik** [comment]
Stopkę i inne zmiany od @kalkson  zmerge'owałem. Wygląda to tak:
![obraz](https://user-images.githubusercontent.com/718163/94464107-4a7c3480-01be-11eb-9bc3-b6cde069a23a.png)

Uważam jednak, że stopka od @madragonse w #11 ma trochę więcej informacji.
![obraz](https://user-images.githubusercontent.com/718163/94464193-726b9800-01be-11eb-9e49-0854e19e1beb.png)

Co powiecie na stopkę w takim stylu:

Created by 
![obraz](https://user-images.githubusercontent.com/718163/94464281-9038fd00-01be-11eb-8b6d-945244f6c91d.png)
at 
![obraz](https://user-images.githubusercontent.com/718163/94464297-96c77480-01be-11eb-9036-bcad016232f8.png)

See source at: (tutaj logo GitHuba w kółku, z linkiem do repo, w stypu pozostałych dwóch).

I wywalenie tego wyskakującego z rogu loga PP (co jest niezgodne z Księgą Znaku PP, patrzcie tu: https://info.put.poznan.pl/sites/default/files/PP_CI_nowelogo04.pdf).

**Comment by kalkson** [comment]
Lepszy pomysł na footer kolegi, z tym że myślę, że czcionka do zmiany na jasną (bo ten zielony jakoś nie siedzi) a pod grafiką logo wywalić napisy i dodać logo politechniki z napisem, a mianowicie:
![image](https://user-images.githubusercontent.com/56680144/94466386-a4cac480-01c1-11eb-85bc-d8416cebad30.png)

**Comment by Gumkle** [comment]
Jeżeli tło ma być ciemne to czcionka jasna, coś jak w pierwszym screenie wysłanym przez Marcina. Loga dosunięte do prawej, logo AKAI zostaje jakie jest i logo polibudy takie jak wysłane  przez @kalkson. Dodanie Githuba jako logo może być, ale trzeba by je zrobić w takim samym stylu jak AKAI i PP, a nie inline w tekście (bo tak chyba @marcinlawnik proponowales?) Żeby uniknąć nadmiarowości to już bym nie pisał see source at. Nie wiem jak z tekstem o wykonaniu przez AKAI w przypadku loga githuba, moze byc czy to juz nadmiar i robi sie tego za duzo?

Takie propozycje z mojej strony

**Comment by madragonse** [comment]
tak zrobię, 3 loga, gdzie te z pp takie duże(@kalkson), napisy jaśniejsze tło jednolite, wydaje mi się że napis "wykonaniu przez AKAI" może zostać @Gumkle

**Comment by Gumkle** [comment]
Issue rozwiązany w #11, zamykam
